keycloak:
  auth-server-url:  http://localhost:8180/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
  security-constraints:
  - authRoles:
    - user
    securityCollections:
    - patterns:
      - /customers/*
